driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_chef-11.4.0.box

suites:
  - name: default
    run_list:
      - recipe[yum-epel::default]
